#!/bin/bash

function link {
  from=$1
  to=$2
  echo "Linking '$to' to '$from'..."
  if [ -e "$to" ]; then
    echo "\tFile $to already exists!"
  elif [ -L "$to" ]; then
    echo "\tLink $to already exists!"
  else
    echo "ln -s \"$from\" \"$to\""
    ln -s "$from" "$to" && echo "\tDone!"
  fi
}

link "$HOME/.vim" "$HOME/.config/nvim"
link "$HOME/.vimrc" "$HOME/.vim/init.vim"

mkdir -p "$HOME/.local/share/nvim/site/autoload"
link "$HOME/.vim/autoload/plug.vim" "$HOME/.local/share/nvim/site/autoload/plug.vim"

link $HOME"/.sublime" \
     $HOME"/Library/Application\ Support/Sublime\ Text\ 3/Packages/User"

