#!/bin/bash

function link {
  from=$1
  to=$2
  # dest="$to/$from"
  echo "Linking '$from' to '$to'..."
  if [ -e "$to" ]; then
    echo -e "\tFile $to already exists!"
  elif [ -L "$to" ]; then
    echo -e "\tLink $to already exists!"
  else
    # ln -s $from $dest && echo -e "\tDone!"
    echo "ln -s $from $dest"
  fi
}

link "$HOME/.vim" "$HOME/.config/nvim"
link "$HOME/.vimrc" "$HOME/.vim/init.vim"

